# permissions for end users to view sleepcycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sleepcycle-viewer-role
rules:
- apiGroups:
  - core.rekuberate.io
  resources:
  - sleepcycles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - sleepcycles/status
  verbs:
  - get
