# permissions for end users to edit sleepcycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sleepcycle-editor-role
rules:
- apiGroups:
  - core.rekuberate.io
  resources:
  - sleepcycles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - sleepcycles/status
  verbs:
  - get
