apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-2
  namespace: app-1
  labels:
    app: app-1-2
    rekuberate.io/sleepcycle: sleepcycle-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1-2
  template:
    metadata:
      name: app-1-2
      labels:
        app: app-1-2
    spec:
      containers:
        - name: app-1-2
          image: traefik/whoami
          imagePullPolicy: IfNotPresent
