apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-1
  namespace: app-1
  labels:
    app: app-1-1
    rekuberate.io/sleepcycle: sleepcycle-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1-1
  template:
    metadata:
      name: app-1-1
      labels:
        app: app-1-1
    spec:
      containers:
        - name: app-1-1
          image: traefik/whoami
          imagePullPolicy: IfNotPresent
